name: Setup ICU4C
description: Download and set up ICU4C libraries

inputs:
  icu-versions-json:
    description: ICU versions JSON object
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set up requirements (Ubuntu)
      if: startsWith(runner.os, 'Linux')
      working-directory: build
      run: |
        curl -fS --retry 3 --retry-delay 5 -LO ${{fromJson(inputs.icu-versions-json).url}}/${{fromJson(inputs.icu-versions-json).icu4c_ubuntu_x64_tgz}}
        sudo tar zxf ${{fromJson(inputs.icu-versions-json).icu4c_ubuntu_x64_tgz}} -C / --strip-components=${{fromJson(inputs.icu-versions-json).strip-components || 2}}
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
      shell: bash

    - name: Set up requirements (Windows)
      if: startsWith(runner.os, 'Windows')
      working-directory: build
      env:
        INSTALL_PREFIX: ${{github.workspace}}/build
        ICU4C_DIR: icu4c
      run: |
        curl -fS --retry 3 --retry-delay 5 -LO ${{fromJson(inputs.icu-versions-json).url}}/${{fromJson(inputs.icu-versions-json).icu4c_win64_zip}}
        7z x ${{fromJson(inputs.icu-versions-json).icu4c_win64_zip}} -o${{env.ICU4C_DIR}}
        if ("x${{fromJson(inputs.icu-versions-json).double_zipped_filename}}" -ne "x") {
          7z x ${{env.ICU4C_DIR}}/${{fromJson(inputs.icu-versions-json).double_zipped_filename}} -o${{env.ICU4C_DIR}}
        }
        echo "ICU_ROOT=${{env.INSTALL_PREFIX}}/${{env.ICU4C_DIR}}" >> $env:GITHUB_ENV
      shell: pwsh
